# Generated by Django 4.2.7 on 2024-02-17 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='crew_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crew',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
