# Generated by Django 4.2.7 on 2024-02-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_crew_write'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='write',
            new_name='writer',
        ),
    ]
