# Generated by Django 4.2.7 on 2024-02-13 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crew', '0003_rename_write_crew_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='crew_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
